### ISSUE TITLE
develop Embedded GUI  using frame buffer 

### ISSUE THREAD

**Issue by myelectropeak** [lvgl/lv_sim_eclipse_sdl#57]
I want to use this tutorial for  embedded Linux frame buffer,
I have encountered two main Issues,
First 
It cant be Cross compile easily 

second
there is no  tutorial   for  using Linux frame buffer

**Comment by kisvegabor** [comment]
Hi,

We have a dedicated project for Linux frame buffer:
https://github.com/lvgl/lv_port_linux_frame_buffer

It should work out of the box. If you have any questions please open an issue in that repository. 

I've updated [related blog post](https://blog.lvgl.io/2018-01-03/linux_fb) too.
