### ISSUE TITLE
[v7.0] Can't run sim: "Launching pc_simulator" has encountered a problem. Program file doesn't exist

### ISSUE THREAD

**Issue by BFFonseca** [lvgl/lv_sim_eclipse_sdl#60]
I'm trying to run the LVGL simulator on dev7.0.
I'm running on ubuntu 18.04 and I've downloaded it through the command line and the used "git checkout dev-7.0".
I then imported the project into Eclipse as the readme says.

I can build the project, but when I try to run it, I get this message:
![image](https://user-images.githubusercontent.com/49754867/83787996-867a0f80-a68c-11ea-9e95-95dcb79c6e17.png)

Any idea why or how I can fix it?

**Comment by embeddedt** [comment]
After checking out `dev-7.0` you need to run `git submodule update --init --recursive` to update the submodules. The build might be failing because of that, so the executable never gets made.

**Comment by BFFonseca** [comment]
> After checking out `dev-7.0` you need to run `git submodule update --init --recursive` to update the submodules. The build might be failing because of that, so the executable never gets made.

I've done this after re-downloading a clean version of the files. Still get the same error after building and running.
![image](https://user-images.githubusercontent.com/49754867/83794373-d5787280-a695-11ea-92e1-e871689181d4.png)

**Comment by embeddedt** [comment]
Try cleaning the project and rebuilding it. Eclipse can behave strangely at times and refuse to actually generate the project.

You can also try clicking on the project in the sidebar and pressing F5 to refresh Eclipse's notion of what files exist.

**Comment by BFFonseca** [comment]
I refresh, cleaned, refreshed, built, refreshed again but still get the same error.
Here's a full screenshot, might help.
![image](https://user-images.githubusercontent.com/49754867/83795288-23da4100-a697-11ea-8fc1-5074b1dbcc84.png)

I suspect it has something to do with the launch configuration, but I have little to no experience with eclipse and have no idea how it works

**Comment by embeddedt** [comment]
I see the problem. The project got renamed, but the launch configuration hasn't been updated to reflect that.

If you go into the "Edit Configuration" window, you can click Browse under C/C++ Application and change it to `Debug/lv_sim_eclipse_sdl_dev`.

**Comment by BFFonseca** [comment]
That did it! I knew it was some detail I didn't know about. 

Thank you!
