### ISSUE TITLE
change default keyboard

### ISSUE THREAD

**Issue by mostafajalal20** [lvgl/lv_sim_eclipse_sdl#63]
hi, how can i change default keyboard from English to another language such as persian, because i read the code and realize that the code have persian keyboard and font ,please help me

**Comment by embeddedt** [comment]
I don't see anything in the core library related to a Persian keyboard; where did you see this?

**Comment by mostafajalal20** [comment]
in lvgl/src/lv_misc/lv_txt_ap.c

**Comment by embeddedt** [comment]
Oh, that's just for handling the rendering of Persian characters. There isn't a built-in Persian keyboard layout; you'd have to create one yourself.

**Comment by mostafajalal20** [comment]
do you have any document or guidance to help me for this?

**Comment by kisvegabor** [comment]
See here: https://docs.lvgl.io/latest/en/html/widgets/keyboard.html#new-keymap

**Comment by mostafajalal20** [comment]
thanks a lot
