### ISSUE TITLE
lv_label_set_text function bug!

### ISSUE THREAD

**Issue by mostafajalal20** [lvgl/lv_sim_eclipse_sdl#64]
hi , when i use this function like this: 
lv_label_set_text(label,"سیب") 
this show nothing in button 
how can i display a non English word such persian or arabic

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
