### ISSUE TITLE
Error when trying to run on Eclipse (macOS)

### ISSUE THREAD

**Issue by david-res** [lvgl/lv_sim_eclipse_sdl#68]
It compiles fine, but when I run it I get the following error
![image](https://user-images.githubusercontent.com/52652879/89732320-a3e5a400-da56-11ea-815b-4b05a658d256.png)
What am I missing?

Im using a 2016 Macbook Pro with the latest OS on Eclipse CDT

**Comment by embeddedt** [comment]
I believe the project name changed but the Eclipse launch configuration wasn't updated. You can try editing the launch configuration and choosing the correct binary (`Debug/lv_sim_eclipse_sdl`, if I recall correctly).

**Comment by david-res** [comment]
@embeddedt that fixed it, thank you!

**Comment by embeddedt** [comment]
Glad to hear it. With https://github.com/lvgl/lv_sim_eclipse_sdl/commit/28f8ed4e60e44cba63cfb2302550a0b7074e8cff it should be fixed upstream as well.
