### ISSUE TITLE
Multiple definitions of main when updating to LVGL 7.3.1

### ISSUE THREAD

**Issue by BFFonseca** [lvgl/lv_sim_eclipse_sdl#69]

**Comment by kisvegabor** [comment]
No problem.

I think issues can't be deleted. :slightly_frowning_face:

**Comment by BFFonseca** [comment]
> I think issues can't be deleted.

Only repository Admins can delete issues. On the right hand side, bottom option.

**Comment by kisvegabor** [comment]
I'm admin, but the issue can be only locked:
![image](https://user-images.githubusercontent.com/7599318/91024375-24c8a200-e5f8-11ea-8d38-ef088c331c79.png)

**Comment by BFFonseca** [comment]
> I'm admin, but the issue can be only locked:

That's weird... I can delete them in my private repositories :thinking:

**Comment by kisvegabor** [comment]
Ah, it was required to be enabled in the organization.
