### ISSUE TITLE
Docker build failure

### ISSUE THREAD

**Issue by martinjankoehler** [lvgl/lv_sim_eclipse_sdl#74]
Running `docker build -t lvgl_simulator .` fails due to:
```bash
#10 7.282 In file included from /pc_simulator_sdl_eclipse/lv_drivers/display/drm.c:9:0:
#10 7.282 /pc_simulator_sdl_eclipse/lv_drivers/display/drm.h:24:5: error: "USE_DRM" is not defined, evaluates to 0 [-Werror=undef]
#10 7.282  #if USE_DRM
#10 7.282      ^~~~~~~
#10 7.282 /pc_simulator_sdl_eclipse/lv_drivers/display/drm.c:10:5: error: "USE_DRM" is not defined, evaluates to 0 [-Werror=undef]
#10 7.282  #if USE_DRM
#10 7.282      ^~~~~~~
```

The reason seems to be that while `USE_DRM` is defined in https://github.com/lvgl/lv_drivers/blob/6a39767f0676cbb8ed28ae9f6d82caf3c6ef1ea7/lv_drv_conf_template.h
it is not in https://github.com/lvgl/lv_sim_eclipse_sdl/blob/master/lv_drv_conf.h

**Comment by kisvegabor** [comment]
Thank you for the fix. :slightly_smiling_face:
