### ISSUE TITLE
lv_sim_vscode_sdl

### ISSUE THREAD

**Issue by microwavesafe** [lvgl/lv_sim_eclipse_sdl#76]
I've created a VSCode project for running LVGL on SDL. I don't use Eclipse, so it was useful to me.

I hand edited the Makefile as that is what I'm familiar with, rather than go the CMake route. Not sure if that makes a difference. Anyway you can just `git clone --recursive https://github.com/microwavesafe/lv_sim_vscode_sdl` the repository, open the workspace and hit F5 to start debugging the example UI.

I'm more than happy for you to take control of the project if it's useful to you.

**Comment by kisvegabor** [comment]
Hi,

That's awesome! I've already dreamed a lot about a VSCode simulator project. :slightly_smiling_face: 

So I'd be happy to host your project here. Of course, you would have admin rights to the repo.

**Comment by microwavesafe** [comment]
I think I can transfer ownership to you through the settings, I've not done this before, is there anything I need to do before that?

**Comment by kisvegabor** [comment]
I also did it only with organizations where I was admin in both, but there wasn't anyhing special.  
I'll simply get a notification about the transfer query.

**Comment by microwavesafe** [comment]
I get this message when I try

```You don’t have the permission to create public repositories on lvgl ```

**Comment by kisvegabor** [comment]
It says you need to have "repository creation permissions" in the target organization. 
https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by kisvegabor** [comment]
I've sent an invitation to temporarily give you "Member access" to the organization.

**Comment by microwavesafe** [comment]
OK that worked, it says it is transferring and may take a few minutes.

**Comment by kisvegabor** [comment]
Great, it already here: https://github.com/lvgl/lv_sim_vscode_sdl
Is it finished on your side too?

**Comment by kisvegabor** [comment]
I see that the commit came from [springltd](https://github.com/springltd). Which user shall give access in the new repo?

**Comment by kisvegabor** [comment]
I've just got a confirmation email about the transfer was successful so withdrawn the access to the whole organization.

**Comment by microwavesafe** [comment]
Yep it's all done here. Sorry that's my work account. I never found a simple way of swapping accounts so I tend to just leave everything as my work account. Add my personal account and I will fix how I access it.

**Comment by kisvegabor** [comment]
I've invited @microwavesafe as admin. 
I can also add @springltd if you wish. From our side, it doesn't really matter if both accounts are yours.

**Comment by microwavesafe** [comment]
Actually that would be useful if you don't mind. I've updated the README with the new url.

**Comment by kisvegabor** [comment]
> Actually that would be useful if you don't mind.

Added. 

>  I've updated the README with the new url.

Thanks!
