### ISSUE TITLE
Docker build is not working on changeset on master head @e151ce7

### ISSUE THREAD

**Issue by lyorak** [lvgl/lv_sim_eclipse_sdl#81]
Git submodule of lv_examples is referring to a changeset that has a warning in lv_examples/src/lv_ex_widgets/lv_ex_keyboard/lv_ex_keyboard_1.c and hence won't build. I see that the issue has been fixed on a later version of ll_examples, should it be bumped in git submodules?

**Comment by lyorak** [comment]
See failing docker build here https://github.com/lyorak/lv_sim_eclipse_sdl/runs/1585216662?check_suite_focus=true

**Comment by kisvegabor** [comment]
@babldev could you take look at it?

**Comment by embeddedt** [comment]
> And this repo was changed from the lv_examples master to 7.8.1.

That was probably caused by the release script.

> Let me know what the best path forward here.

It seems to me that it would be simplest to just release 7.8.2.

**Comment by babldev** [comment]
I agree, sounds like a plan

**Comment by babldev** [comment]
A note going forward on this approach is we shouldn't directly modify the submodules, and instead cut a relesae

**Comment by kisvegabor** [comment]
Thanks for checking it.

I've just updated `lv_examples` to `master`. It will be part of the next release.

**Comment by lyorak** [comment]
As I see updating the submodule itself did not solve the issue, just ended up in another compilation error. A 
See https://github.com/lyorak/lv_sim_eclipse_sdl/runs/1600083761?check_suite_focus=true 
The macro LV_USE_DEMO_MUSIC is missing from lv_ex_conf.h

**Comment by kisvegabor** [comment]
@lyorak Added: https://github.com/lvgl/lv_sim_eclipse_sdl/commit/0521232b720e8c38069668e36318c793e4f3dc97

**Comment by embeddedt** [comment]
@kisvegabor Something is wrong with the update script. The commit message says "Update to 7.9.0" but the actual [`release/v7`]( https://github.com/lvgl/lv_examples/tree/release/v7) branch on `lv_examples` is stuck on a commit from the beginning of December. I think that is part of the problem here.

**Comment by kisvegabor** [comment]
I've added a fix after the last release. It failed to correctly update the repo if there were no changes. 
We will see how it works with today's release.

**Comment by kisvegabor** [comment]
As the issue seems to be solved I close it.

If it's still not working please reopen the issue and comment here.
