### ISSUE TITLE
SDL2/SDL.h'

### ISSUE THREAD

**Issue by aspdigital** [lvgl/lv_sim_eclipse_sdl#94]
on macOS 11 Big Sur: I downloaded and installed the SDL framework into /Library/Frameworks as instructed. I installed a fresh new Eclipse and cloned the simulator, imported into my Eclipse workspace, tried to build it and got a "fatal error: 'SDL2/SDL.h'" in keyboard.h.

I suppose the ur question is how to configure Eclipse to find SDL.h.

In /Library/Frameworks/SDL2.framework there's a symlink called SDL2 but that points to an executable called SDL2. The actual header is in SDL2.framework/Headers/SDL.h

So should I edit the offending keyboard.h (and all other files that refer to SDL.h), or edit the Frameworks to rename the directory SDL2.framework to simply SDL2, or something else? And then add it to my Eclipse includes list.

**Comment by embeddedt** [comment]
You can configure the exact include path in the [`lv_drv_conf.h`](https://github.com/lvgl/lv_sim_eclipse_sdl/blob/e164e3591c3e1e3bf3464d19e0dcdc67b2e6a791/lv_drv_conf.h#L101) file.

I don't have access to a Mac, so I am unfortunately unable to help much further (hopefully someone else can!), however, from some quick and limited research:

* `<SDL.h>` looks like the proper include name to use.
* `/Library/Frameworks/SDL2.framework/Headers` needs to be added to your Eclipse include path.

That should make compilation succeed but you might run into more errors when it gets to the linking stage.

**Comment by aspdigital** [comment]
I put a symlink in /Library/Frameworks called SDL2 which links to SDL2.framework.Headers 

and that somewhat resolves the problem. Now I get:

warning: 'MONITOR_SDL_INCLUDE_PATH' macro redefined

in the various disabled display driver headers.

As expected, there are linker issues:

ld: library not found for -lSDL2main

I see that SDL2main is called out in my C/C++ Build -> Settings -> Linker -> Libraries, but I have no idea where it's supposed to live, or what builds it, etc.

I was hoping to not go down such a rabbit hole.

**Comment by kisvegabor** [comment]
Have you installed SDL2 with `brew install sdl2`? 
The last time when I tested on Mac it worked with any extra modifications.
